= Strimzi Kafka CLI

Strimzi Kafka CLI is a CLI that helps traditional Apache Kafka users -mostly administrators- to easily adapt https://strimzi.io/[Strimzi], a https://operatorhub.io/operator/strimzi-kafka-operator[Kubernetes operator] for https://kafka.apache.org/[Apache Kafka]. Strongly inspired by https://github.com/tektoncd/cli[Tekton CLI].

Intention here is to ramp up Strimzi usage by creating a similar CLI experience with traditional Apache Kafka binaries. For example:


[width="100%",options="header,footer"]
|====================
| Native Command | Strimzi CLI Command
| kafka-topics.sh |  kfk topics
| kafka-configs.sh |  kfk configs
| kafka-console-consumer.sh |  kfk console-consumer
|====================


*kfk* command stands for the traditional kafka-* prefix of the Apache Kafka runnable files which are located in _bin_ directory. There are options provided like _topics_, __console-consumer__, etc. which also mostly stand for the rest of the runnable file names like _kafka-topic.sh_. However, because of the nature of Strimzi and its capabilities, there are also non-traditional options like _clusters_ which is used for cluster configuration or _users_ which is used for user management and configuration.

Following is the high-level output of the Strimzi Kafka CLI:

[source,bash]
----
Usage: kfk [OPTIONS] COMMAND [ARGS]...

  Strimzi Kafka CLI

Options:
  --help  Show this message and exit.

Commands:
  clusters          The kafka cluster(s) to be created, altered or...
  configs           Add/Remove entity config for a topic, client, user or...
  console-consumer  The console consumer is a tool that reads data from...
  console-producer  The console producer is a tool that reads data from...
  topics            The kafka topic(s) to be created, altered or described.
  users             The kafka user(s) to be created, altered or described.
----

More info will be added soon.
