# This is a basic workflow to help you get started with Actions

name: Bake

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  watch:
    types: [started]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  bake:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Get version
      run: echo ::set-env name=STRIMZI_CLI_VERSION::$(grep -oP "(?<=version=')[^']*" setup.py)
    - name: Test
      run: echo $GITHUB_SHA_SHORT
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: ${{ secrets.QUAY_USERNAME }}
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.QUAY_PASSWORD }}
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: quay.io
        # Docker repository to tag the image with
        repository: systemcraftsman/strimzi-kafka-cli
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: latest,${{ env.STRIMZI_CLI_VERSION }}
        # Path to the build context
        path: .
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        dockerfile: ./Dockerfile
        # Whether to push the image
        push: true
