# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4
    - name: Install setuptools for Python ${{ matrix.python-version }}
      run: python -m pip install --upgrade setuptools


    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: make install-dependencies

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.0

    - uses: actions/checkout@v4
    - name: Retrieve the kubeconfig and decode it to a file
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        mkdir ~/.kube
        echo $KUBECONFIG
        echo $KUBECONFIG > ~/.kube/config

    - name: Test
      run: |
        kfk
        make test
    - name: Build
      run: make build
